### ISSUE TITLE
Book does not generate

### ISSUE THREAD

**Issue by Jeannotisintheplace** [wsexport/tool#225]
Hi,
trying to generate .mobi from the book here:

https://fr.wikisource.org/wiki/Le_Calvaire

and experiencing this error message:

The command "'ebook-convert' '/tmp/www-data/ws-c0_Le_Calvaire-268021020883056.epub' '/tmp/www-data/ws-c0_Le_Calvaire-268021947320341.mobi' '--page-breaks-before' '/'" failed.

Exit Code: 1(General error)

Working directory: /var/www/tool/public

Output:
================
1% Converting input to HTML...
InputFormatPlugin: EPUB Input running
on /tmp/www-data/ws-c0_Le_Calvaire-268021020883056.epub

Error Output:
================
Traceback (most recent call last):
File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 241, in find_opf
File "site-packages/calibre/startup.py", line 192, in local_open
IOError: [Errno 2] No such file or directory: u'META-INF/container.xml'
Traceback (most recent call last):
File "site.py", line 77, in main
File "site-packages/calibre/ebooks/conversion/cli.py", line 401, in main
File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
File "site-packages/calibre/customize/conversion.py", line 246, in __call__
File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 281, in convert
ValueError: /tmp/www-data/ws-c0_Le_Calvaire-268021020883056.epub is not a valid EPUB file (could not find opf)

**Comment by Tpt** [comment]
Thank you for the bug report!

I do not manage to reproduce it on https://wsexport.wmflabs.org/: https://wsexport.wmflabs.org/tool/book.php?lang=fr&format=mobi&page=Le_Calvaire
Are you using https://wsexport.wmflabs.org (what French Wikisource links to) or an other server?

**Comment by samwilson** [comment]
This may have been a intermittent error perhaps; it's no longer happening.

@Jeannotisintheplace if you are still experiencing this, could you please open a new issue on [Phabricator](https://phabricator.wikimedia.org/)? Thanks!
